---
- hosts: all
  pre_tasks:
  - name: Install Homebrew
    shell: 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
    args:
      creates: /usr/local/bin/brew
  - name: Update Homebrew
    homebrew: update_homebrew=yes
  - name: Add Caskroom versions tap
    homebrew_tap: tap=caskroom/versions state=present

- hosts: all
  tasks:
  - name: Install git without completions
    homebrew: name=git state=present install_options=--without-completions,--with-brewed-openssl,--with-brewed-curl
  - name: Install Homebrew packages without config
    homebrew: name={{ item }} state=present
    with_items:
      - duti
      - tig
      - hub
      - unrar
      - wakeonlan
      - weechat
      - wget
      - zsh
      - zsh-completions
      - stow
      - docker-machine
      - docker
      - groovysdk
      - python3
  - name: Install Homebrew Cask packages without config
    homebrew_cask: name={{ item }} state=present
    with_items:
      - android-file-transfer
      - arduino
      - caffeine
      - dropbox
      - firefox
      - flux
      - gimp
      - google-chrome
      - google-drive
      - iterm2-beta
      - itsycal
      - keepassx
      - rightzoom
      - silicon-labs-vcp-driver
      - slack
      - atom
      - the-unarchiver
      - vlc
      - xtrafinder
      - spectacle
      - steam
      - intellij-idea-ce
      - virtualbox
      - java
      - tunnelblick
  - name: Install Python packages
    become: yes
    pip: executable=pip3 name={{ item }} state=present
    with_items:
      - pylint
      - pyserial
      - todotxt-machine
  - name: Create curl-ca-bundle directory
    file: path=/etc/ssl/certs/ state=directory owner=root group=wheel
    become: true
  - name: Install curl-ca-bundle
    get_url: url=https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt dest=/etc/ssl/certs/ca-certificates.crt mode=0644
    become: true
