---
- hosts: all
  pre_tasks:
  - name: Install Homebrew
    shell: 'ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"'
    args:
      creates: /usr/local/bin/brew
  - name: Update Homebrew
    homebrew: update_homebrew=yes
  - name: Add Caskroom versions tap
    homebrew_tap: tap=caskroom/versions state=present
  - name: Add dinghy tap
    homebrew_tap: tap=codekitchen/dinghy state=present

- hosts: all
  tasks:
  - name: Install git without completions
    homebrew: name=git state=present install_options=--without-completions,--with-brewed-openssl,--with-brewed-curl
  - name: Install Homebrew packages without config
    homebrew: name={{ item }} state=present
    with_items:
      - android-platform-tools
      - dinghy
      - docker
      - duti
      - fasd
      - git
      - groovysdk
      - hub
      - jq
      - ncdu
      - pwgen
      - python3
      - stow
      - tig
      - tree
      - unrar
      - wakeonlan
      - weechat
      - wget
      - zsh
      - zsh-completions
  - name: Install Homebrew packages that need to be linked explicitly
    homebrew: name={{ item }} state=present
    with_items:
      - gettext
  - name: Install Homebrew Cask packages without config
    homebrew_cask: name={{ item }} install_options='force' state=present
    with_items:
      - android-file-transfer
      - arduino
      - atom
      - caffeine
      - dropbox
      - firefox
      - flux
      - gimp
      - google-chrome
      - google-drive
      - intellij-idea-ce
      - iterm2
      - itsycal
      - java
      - keepassx
      - silicon-labs-vcp-driver
      - slack
      - spectacle
      - the-unarchiver
      - tunnelblick
      - vagrant
      - virtualbox
      - vlc
      - xtrafinder
  - name: Update file type association
    become: true
    command: "duti ./duti"
  - name: Install Python packages
    become: yes
    pip: executable=pip3 name={{ item }} state=present
    with_items:
      - pylint
      - pyserial
      - todotxt-machine
  - name: Create curl-ca-bundle directory
    file: path=/etc/ssl/certs/ state=directory owner=root group=wheel
    become: true
  - name: Install curl-ca-bundle
    get_url: url=https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt dest=/etc/ssl/certs/ca-certificates.crt mode=0644
    become: true
